In [411]:
import numpy as np

In [412]:
A = np.matrix([[7.03, 1.22, 0.85, 1.135, -0.81],
     [0.98, 3.39, 1.3, -1.63, 0.57],
     [1.09, -2.46, 6.21, 2.1, 1.033],
     [1.345, 0.16, 2.1, 5.33, -12],
     [1.29, -1.23, -0.767, 6, 1]])
b = np.matrix([[2.1],
     [0.84],
     [2.58],
     [11.96],
     [-1.47]])
n = 5

In [413]:
def m_i(matrix, p, q):
    m = np.empty(n)
    i = 0
    while i != p:
        m[i] = (matrix.item(i,q) / matrix.item(p,q))
        i = i + 1    
    i = i + 1
    while i != n:
        m[i] = (matrix.item(i,q) / matrix.item(p,q))
        i = i + 1
    m[p] = 0
    return m

def absmaxND(a, axis=None):
    amax = a.max(axis)
    amin = a.min(axis)
    return np.where(-amin > amax, amin, amax)

A_k = A
b_k = b
while n - 1 > 1:
    ##a_max = A_k.max()
    a_max = A_k.flat[np.abs(A_k).argmax()]  
    p, q = np.unravel_index(abs(A_k).argmax(), A_k.shape)
    m = m_i(A_k, p, q)
    for i in range(n):
        A_k[i] = A_k[i] - m[i] * A_k[p]
        b_k[i] = b_k[i] - m[i] * b_k[p]
        i = i + 1
    print(f"{A_k}\n")
    print(f"{b_k}\n")
    A_k = np.delete(A_k, p, 0)
    A_k = np.delete(A_k, q, 1)
    b_k = np.delete(b_k, p, 0)
    n = n - 1




[[  6.9392125    1.2092       0.70825      0.775225     0.        ]
 [  1.0438875    3.3976       1.39975     -1.376825     0.        ]
 [  1.20578208  -2.44622667   6.390775     2.55882417   0.        ]
 [  1.345        0.16         2.1          5.33       -12.        ]
 [  1.40208333  -1.21666667  -0.592        6.44416667   0.        ]]

[[ 1.2927    ]
 [ 1.4081    ]
 [ 3.60955667]
 [11.96      ]
 [-0.47333333]]

[[ 6.9392125   1.2092      0.70825     0.775225  ]
 [ 0.          3.21569625  1.29320573 -1.49344453]
 [ 0.         -2.65634153  6.26770698  2.42411833]
 [ 0.         -1.46098822 -0.73510349  6.28753073]]

[[ 1.2927    ]
 [ 1.21363508]
 [ 3.38493255]
 [-0.73452625]]

[[ 2.86867531  1.11860042  0.        ]
 [-2.09306662  6.55112155  0.        ]
 [-1.46098822 -0.73510349  6.28753073]]

[[ 1.03916688]
 [ 3.66812457]
 [-0.73452625]]

