In [29]:
import numpy as np
np.set_printoptions(precision=2)

In [30]:
A = np.matrix([[7.03, 1.22, 0.85, 1.135, -0.81],
     [0.98, 3.39, 1.3, -1.63, 0.57],
     [1.09, -2.46, 6.21, 2.1, 1.033],
     [1.345, 0.16, 2.1, 5.33, -12],
     [1.29, -1.23, -0.767, 6, 1]])
b = np.matrix([[2.1],
     [0.84],
     [2.58],
     [11.96],
     [-1.47]])
n = 5


\begin{equation*}
A = 
\begin{pmatrix}
7.03 & 1.22 & 0.85 & 1.135 & -0.81\\
0.98 & 3.39 & 1.3 & 1.63 & 0.57\\
1.09 & -2.46 & 6.21 & 2.1 & 1.033\\
1.345 & 0.16 & 2.1 & 5.33 & -12\\
1.29 & -1.23 & -0.767 & 6 & 1
\end{pmatrix}
\end{equation*}

\begin{equation*}
b = 
\begin{pmatrix}
2.1 \\
0.84 \\
2.58 \\
11.96 \\
-1.47 
\end{pmatrix}
\end{equation*}

In [31]:
A_k = A.copy()
b_k = b.copy()
x = np.zeros(n)

j = 0
for i in range(n):
    for j in range(n):
        if j != i:
            b_k[j] = b_k[j] - (A_k.item(j, i) / A_k.item(i, i)) * b_k[i]
            A_k[j] = A_k[j] - (A_k.item(j, i) / A_k.item(i, i)) * A_k[i]
            print(f"{i}.{j}: \n {A_k} \n\n {b_k} \n\n")
for i in range(n):
    x[i] = b_k[i] / A_k.item(i,i)
print(f"x = {x}\n\n")
mat = np.asmatrix(x)
mat1 = mat.getT()


print(f"Перевірка:\n\n {A * mat1 - b}")


0.1: 
 [[  7.03   1.22   0.85   1.14  -0.81]
 [  0.     3.22   1.18  -1.79   0.68]
 [  1.09  -2.46   6.21   2.1    1.03]
 [  1.34   0.16   2.1    5.33 -12.  ]
 [  1.29  -1.23  -0.77   6.     1.  ]] 

 [[ 2.1 ]
 [ 0.55]
 [ 2.58]
 [11.96]
 [-1.47]] 


0.2: 
 [[  7.03   1.22   0.85   1.14  -0.81]
 [  0.     3.22   1.18  -1.79   0.68]
 [  0.    -2.65   6.08   1.92   1.16]
 [  1.34   0.16   2.1    5.33 -12.  ]
 [  1.29  -1.23  -0.77   6.     1.  ]] 

 [[ 2.1 ]
 [ 0.55]
 [ 2.25]
 [11.96]
 [-1.47]] 


0.3: 
 [[  7.03   1.22   0.85   1.14  -0.81]
 [  0.     3.22   1.18  -1.79   0.68]
 [  0.    -2.65   6.08   1.92   1.16]
 [  0.    -0.07   1.94   5.11 -11.85]
 [  1.29  -1.23  -0.77   6.     1.  ]] 

 [[ 2.1 ]
 [ 0.55]
 [ 2.25]
 [11.56]
 [-1.47]] 


0.4: 
 [[  7.03   1.22   0.85   1.14  -0.81]
 [  0.     3.22   1.18  -1.79   0.68]
 [  0.    -2.65   6.08   1.92   1.16]
 [  0.    -0.07   1.94   5.11 -11.85]
 [  0.    -1.45  -0.92   5.79   1.15]] 

 [[ 2.1 ]
 [ 0.55]
 [ 2.25]
 [11.56]
 [-1.86]] 




In [32]:
def m_i(matrix, p, q):
    m = np.zeros(n)
    i = 0
    while i != n:
        if i != p:
            ##print(f"----------------- \n\n {matrix.item(i,q)} \n {matrix.item(p,q)}")
            m[i] = (matrix.item(i,q) / matrix.item(p,q))
            ##print(f"{m[i]}\n\n ----------------- ")
        i = i + 1
    m[p] = 0
    return m

A_k = A.copy()
b_k = b.copy()
x = np.zeros(n)

while n - 1 > 1:
    a_max = A_k.flat[np.abs(A_k).argmax()]  
    p, q = np.unravel_index(abs(A_k).argmax(), A_k.shape)
    m = m_i(A_k, p, q)

    for i in range(n):
        ##print(f"{i}  {A_k[p]} \n {A_k[p] * m[i]} \n")
        ##print(f"{A_k[i]} \n")
        A_k[i] = A_k[i] - (m[i] * A_k[p])
        ##print(f"{A_k[i]} \n")
        b_k[i] = b_k[i] - (m[i] * b_k[p])

    ##print(f"{p} \n {q} \n")
    ##print(f"{b_k} \n\n {A_k} \n")
    ##print(f"{b_k.item(p, 0)} \n {A_k.item(p,q)} \n")
    x[p] = b_k.item(p, 0) / A_k.item(p,q)
    ##print(f"{x[p]} \n\n")
    A_k = np.delete(A_k, p, 0)
    A_k = np.delete(A_k, q, 1)
    b_k = np.delete(b_k, p, 0)
    n = n - 1

mat = np.asmatrix(x)
mat1 = mat.getT()
##print("|"*20)
##print(f"{A} \n\n {mat1} \n\n {b} \n\n")
##print(A * mat1 - b)

